package com.dao.Pojo;

import java.util.Date;

public class SaleComments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_comments.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_comments.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_comments.sale_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_comments.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_comments.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_comments.id
     *
     * @return the value of sale_comments.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_comments.id
     *
     * @param id the value for sale_comments.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_comments.timestamp
     *
     * @return the value of sale_comments.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_comments.timestamp
     *
     * @param timestamp the value for sale_comments.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_comments.sale_id
     *
     * @return the value of sale_comments.sale_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_comments.sale_id
     *
     * @param saleId the value for sale_comments.sale_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_comments.user_id
     *
     * @return the value of sale_comments.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_comments.user_id
     *
     * @param userId the value for sale_comments.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_comments.text
     *
     * @return the value of sale_comments.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_comments.text
     *
     * @param text the value for sale_comments.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}