package com.dao.Pojo;

import java.util.Date;

public class Sales {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.title
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.price
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.location
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.category
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.id
     *
     * @return the value of sales.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.id
     *
     * @param id the value for sales.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.title
     *
     * @return the value of sales.title
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.title
     *
     * @param title the value for sales.title
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.price
     *
     * @return the value of sales.price
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.price
     *
     * @param price the value for sales.price
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.location
     *
     * @return the value of sales.location
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.location
     *
     * @param location the value for sales.location
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.category
     *
     * @return the value of sales.category
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.category
     *
     * @param category the value for sales.category
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.user_id
     *
     * @return the value of sales.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.user_id
     *
     * @param userId the value for sales.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.timestamp
     *
     * @return the value of sales.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.timestamp
     *
     * @param timestamp the value for sales.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.text
     *
     * @return the value of sales.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.text
     *
     * @param text the value for sales.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}