package com.dao.Pojo;

import java.util.Date;

public class Statuses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statuses.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statuses.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statuses.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statuses.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statuses.id
     *
     * @return the value of statuses.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statuses.id
     *
     * @param id the value for statuses.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statuses.timestamp
     *
     * @return the value of statuses.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statuses.timestamp
     *
     * @param timestamp the value for statuses.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statuses.user_id
     *
     * @return the value of statuses.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statuses.user_id
     *
     * @param userId the value for statuses.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statuses.text
     *
     * @return the value of statuses.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statuses.text
     *
     * @param text the value for statuses.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}