package com.dao.Pojo;

import java.util.Date;

public class StatusReplies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_replies.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_replies.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_replies.status_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_replies.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_replies.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_replies.id
     *
     * @return the value of status_replies.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_replies.id
     *
     * @param id the value for status_replies.id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_replies.timestamp
     *
     * @return the value of status_replies.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_replies.timestamp
     *
     * @param timestamp the value for status_replies.timestamp
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_replies.status_id
     *
     * @return the value of status_replies.status_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_replies.status_id
     *
     * @param statusId the value for status_replies.status_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_replies.user_id
     *
     * @return the value of status_replies.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_replies.user_id
     *
     * @param userId the value for status_replies.user_id
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_replies.text
     *
     * @return the value of status_replies.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_replies.text
     *
     * @param text the value for status_replies.text
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}