package com.dao.Mapper;

import com.dao.Pojo.Sales;
import com.dao.Pojo.SalesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    long countByExample(SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int deleteByExample(SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int insertSelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    List<Sales> selectByExampleWithBLOBs(SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    List<Sales> selectByExample(SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    Sales selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sales record, @Param("example") SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Sales record, @Param("example") SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExample(@Param("record") Sales record, @Param("example") SalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKeySelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKey(Sales record);
}