package com.dao.Mapper;

import com.dao.Pojo.SaleComments;
import com.dao.Pojo.SaleCommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    long countByExample(SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int deleteByExample(SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int insert(SaleComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int insertSelective(SaleComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    List<SaleComments> selectByExampleWithBLOBs(SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    List<SaleComments> selectByExample(SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    SaleComments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleComments record, @Param("example") SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SaleComments record, @Param("example") SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByExample(@Param("record") SaleComments record, @Param("example") SaleCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKeySelective(SaleComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SaleComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_comments
     *
     * @mbg.generated Sun Oct 21 14:39:24 CST 2018
     */
    int updateByPrimaryKey(SaleComments record);
}